# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ecommerce_app_development
  username: devops
  password: devops
  host: localhost
  port: 5432

test:
  <<: *default
  database: ecommerce_app_test
  username: devops
  password: devops
  host: localhost
  port: 5432

production:
  <<: *default
  database: ecommerce_app_production
  username: ecommerce_app
  password: <%= ENV["ECOMMERCE_APP_DATABASE_PASSWORD"] %>
  host: localhost
  port: 5432
